---
title: "Mini-Project 2"
author: "Lisa Chen and Yejin Hwang"
date: "October 31, 2017"
output: html_document
---

```{r,eval=FALSE}
## Loading the data
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, include=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r, eval=FALSE}
# selected columns for smaller dataframes and saved
candidate_info <- candidates %>%
  select(cand_id, cand_name, cand_party_affiliation, cand_election_yr, cand_office)

save(candidate_info,file="candidate_info.rda")
glimpse(candidate_info)

committee_info <- committees %>%
  select(cmte_id, org_type, cand_id)

save(committee_info,file="committee_info.rda")
glimpse(committee_info)

contribution_info <- contributions %>%
  select(cmte_id,transaction_amt,cand_id)

save(contribution_info,file="contribution_info.rda")
glimpse(contribution_info)
```

```{r}
load("candidate_info.rda")
load("committee_info.rda")
load("contribution_info.rda")

join_two <- contribution_info %>%
  inner_join(candidate_info, by = c("cand_id"="cand_id"))

joined_three <- join_two %>%
  inner_join(committee_info, by = c("cmte_id"="cmte_id"))

joined_three <- joined_three %>%
  filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP") %>%
  filter(cand_election_yr >=2009 & cand_election_yr <=2013)
```
```{r}
house <- joined_three %>%
  filter(cand_office == 'H')
senate <- joined_three %>%
  filter(cand_office == 'S')
presidential <- joined_three %>%
  filter(cand_office == 'P')
```
```{r}
FilL <- c("#232066", "#E91D0E")
by_office <- function(dtfrm){
  ggplot(data = dtfrm, aes(x = cand_election_yr, y=transaction_amt, color = cand_party_affiliation), alpha = 0.2) +
  #for individual points to be seen, usage of jitter
  geom_jitter() +
  scale_color_manual(values=FilL, alpha(FilL,alpha = 0.2)) +
  facet_wrap(~org_type)
}

#by_office(house)
office_dtfrmes <- list(house, senate, presidential)
lapply(office_dtfrmes, FUN = by_office)
```

```{r}
FilL <- c("#232066", "#E91D0E")
by_office_bar <- function(dtfrm){
  dtfrm_b <- dtfrm %>%
    group_by(org_type, cand_party_affiliation) %>%
    summarize(trans_amt = sum(transaction_amt))
  ggplot(data = dtfrm_b, aes(x = org_type, y=trans_amt, fill = cand_party_affiliation, color = cand_party_affiliation)) +
  #for individual points to be seen, usage of jitter
  geom_bar(position="dodge", stat="identity") +
  scale_fill_manual(values=FilL)
}

#by_office_bar(house)
office_dtfrmes <- list(house, senate, presidential)
lapply(office_dtfrmes, FUN = by_office_bar)
```


```{r}
pres_plot <- ggplot(data = presidential,aes(x = cand_election_yr, y=transaction_amt, color = cand_party_affiliation), alpha = 0.2) +
  #for individual points to be seen, usage of jitter
  geom_jitter() +
  scale_color_manual(values=FilL, alpha(FilL,alpha = 0.2))
pres_plot
```


